command: ["streamlit", "run", "app.py"]
env:
  - name: GENIE_SPACE_ID
    valueFrom: genie-space
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
